### ISSUE TITLE
エラーログ

### ISSUE THREAD

**Issue by BlackBlastRavenSub** [KOGUMA0608/MontyHallGame#1]
02-25 02:36:57.880 1591-1591/com.game.blastraven.b.montyhallgame E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.game.blastraven.b.montyhallgame, PID: 1591
                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.game.blastraven.b.montyhallgame/com.game.blastraven.b.montyhallgame.GameCoreActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                       at android.os.Looper.loop(Looper.java:156)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                                                                                       at com.game.blastraven.b.montyhallgame.GameCoreActivity.onCreate(GameCoreActivity.java:60)
                                                                                       at android.app.Activity.performCreate(Activity.java:6910)
                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
                                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                       at android.os.Looper.loop(Looper.java:156) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6595) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by nshiba** [comment]
https://github.com/KOGUMA0608/MontyHallGame/blob/master/app/src/main/java/com/game/blastraven/b/montyhallgame/GameCoreActivity.java#L60
でぬるぽはいてる

これhttps://github.com/KOGUMA0608/MontyHallGame/blob/master/app/src/main/java/com/game/blastraven/b/montyhallgame/GameCoreActivity.java#L44で `Game` オブジェクトを初期化してるけど、このとき `stage` はnullで初期化されてるから単純にぬるぽでしんでるっぽい

**Comment by nshiba** [comment]
https://github.com/KOGUMA0608/MontyHallGame/blob/master/app/src/main/java/com/game/blastraven/b/montyhallgame/GameCoreActivity.java#L47
でTextViewの初期化してるんだけど、Viewはレンダリングされた後、つまりonCreate関数が呼ばれた後じゃないと(Android Lifecycleの関係上)取得できないのでonCreate内で `findViewById` をたたく必要がある
